version: "3"

services:
  web:
    build: .
    container_name: app
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - |
        yarn dev
